---

php_ini:
  - option: "error_reporting"
    section: "global"
    value: "E_ALL"
  - option: "display_errors"
    section: "global"
    value: "On"
  - option: "memory_limit"
    section: "global"
    value: "512M"
  - option: "date.timezone"
    section: "global"
    value: "{{ timezone }}"

php_apcu_ini:
  - option: "apc.enable_cli"
    section: "global"
    value: "On"
  - option: "apc.shm_size"
    section: "global"
    value: "256M"
  - option: "apc.mmap_file_mask"
    section: "global"
    value: "/var/tmp/apc.XXXXXX"

php_xdebug_ini:
  - option: "xdebug.cli_color"
    section: "xdebug"
    value: "1"
  - option: "xdebug.idekey"
    section: "xdebug"
    value: "PHPSTORM-XDEBUG"
  - option: "xdebug.max_nesting_level"
    section: "xdebug"
    value: "500"
  - option: "xdebug.profiler_enable"
    section: "xdebug"
    value: "0"
  - option: "xdebug.profiler_enable_trigger"
    section: "xdebug"
    value: "1"
  - option: "xdebug.remote_connect_back"
    section: "xdebug"
    value: "On"
  - option: "xdebug.remote_enable"
    section: "xdebug"
    value: "on"
  - option: "xdebug.remote_port"
    section: "xdebug"
    value: "9000"
  - option: "xdebug.show_mem_delta"
    section: "xdebug"
    value: "1"
  - option: "xdebug.var_display_max_depth"
    section: "xdebug"
    value: "5"

php_opcache_ini:
  - option: "opcache.memory_consumption"
    section: "opcache"
    value: "256"
  - option: "opcache.interned_strings_buffer"
    section: "opcache"
    value: "8"
  - option: "opcache.max_accelerated_files"
    section: "opcache"
    value: "4000"
  - option: "opcache.revalidate_freq"
    section: "opcache"
    value: "60"
  - option: "opcache.fast_shutdown"
    section: "opcache"
    value: "1"
  - option: "opcache.enable_cli"
    section: "opcache"
    value: "1"
  - option: "opcache.enable"
    section: "opcache"
    value: "1"

php_enabled_modules: []

php_disabled_modules: [ apcu ]

php_brew_enable: no

php_brew_required_packages:
  - 'libmariadbclient-dev'
  - 'libmariadbd-dev'
  - 'libmcrypt-dev'
  - 'libreadline-dev'
  - 'libxml2-dev'

php_common_packages:
  - 'php-pear'
  - 'php5-apcu'
  - 'php5-cli'
  - 'php5-curl'
  - 'php5-gd'
  - 'php5-json'
  - 'php5-mcrypt'
  - 'php5-memcache'
  - 'php5-mysqlnd'
  - 'php5-xdebug'
  - 'php5-xhprof'

php_disabled_modules:
  - blackfire
  - redis
  - xdebug
  - xhprof

php_enabled_modules:
  - apcu
  - mcrypt
