---

- name: Make the webroot exists
  file: path={{ typo3_webroot }} state=directory mode=0775
  tags: [typo3-configuration]

- name: Is the webroot a mountpoint (web share enabled)?
  command: mountpoint {{ typo3_webroot }}
  ignore_errors: yes
  register: shared_webroot
  tags: [typo3-configuration]

- name: Make sure vagrant can write to the webroot
  file: path={{ typo3_webroot }} state=directory owner=vagrant group={{nginx_group}} mode=0775
  when: "'is not a mountpoint' in shared_webroot.stdout"
  tags: [typo3-configuration]

- name: Increase composer timeout to fifteen minutes
  command: composer config --global process-timeout 900

- name: Generate ssl certificates for nginx sites (needs to run before nginx role)
  command: openssl req -x509 -sha512 -nodes -days 3650 -subj '/C=NL/ST=Noord-Brabant/O=MaxServ/L=Giessen/CN={{ item }}' -newkey rsa:4096 -keyout /etc/ssl/private/{{ item | regex_replace('^\\*\\.(.*)', '\\1') }}.key -out /etc/ssl/certs/{{ item | regex_replace('^\\*\\.(.*)', '\\1') }}.crt creates=/etc/ssl/certs/{{ item | regex_replace('^\\*\\.(.*)', '\\1') }}.crt
  with_items: typo3_ssl_certificates
  notify:
    - reload nginx
  tags: [typo3-configuration,nginx,ssl]

- name: Setup push url to review.typo3.org
  sudo: vagrant
  shell: git config --global url."ssh://{{ typo3_org_username }}@review.typo3.org:29418".pushInsteadOf git://git.typo3.org
  tags: [typo3-git-setup]

- include: defaultSite.yml
  tags: [typo3-defaultSite]

- include: mariadb.yml
  tags: [typo3-mariadb]

- include: cms.yml
  tags: [typo3-cms]

- include: cron.yml
  tags: [typo3-cron]

- include: neos.yml
  tags: [typo3-neos]

- name: Ensure the root user bin dir exists
  file: path=/root/bin state=directory mode=0775
  tags: [typo3-ramdisk]

- name: Create a script that enforces mounting the ramdisks after reboot
  template: src=mountTypo3Temp.sh.j2 dest=/root/bin/mountTypo3Temp.sh mode=u+rwx
  tags: [typo3-ramdisk]
