---

- name: Add Key for MariaDB Repository
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name: Add MariaDB-Repository
  apt_repository: repo='deb http://mirror3.layerjet.com/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main' state=present

- name: Update apt
  apt: update_cache=yes

- name: Install MariaDB Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Set the MySQL root password
  mysql_user: user=root
              password={{ mariadb.root_password }}
              host={{ item }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Setup MySQL credentials for root user
  template: src=mysql.conf.j2 dest=~/.my.cnf owner=root mode=0600

- name: Setup MySQL credentials for vagrant user
  template: src=mysql.conf.j2 dest=/home/vagrant/.my.cnf owner=vagrant mode=0600

- name: Delete blank MySQL users
  mysql_user: name="" host={{ item }} state=absent
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Drop MySQL test database
  mysql_db: name=test state=absent

- name: Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mariadb.root_password }} login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Customize MySQL configuration file
  lineinfile: dest={{ mariadb.conf_path }} regexp="^tmpdir\s*=\s/tmp" line="tmpdir = /run/shm" backrefs=yes
  notify:
   - restart mysql
  tags: lala