---
php_common_ppa: php5

php_fpm_ini_path: /etc/php5/fpm/php.ini
php_cli_ini_path: /etc/php5/cli/php.ini
php_apcu_ini_path: /etc/php5/mods-available/apcu.ini
php_opcache_ini_path: /etc/php5/mods-available/opcache.ini
php_xdebug_ini_path: /etc/php5/mods-available/xdebug.ini

php_blackfire_enable: no

php_common_packages:
    - 'php-pear'
    - 'php5-apcu'
    - 'php5-cli'
    - 'php5-curl'
    - 'php5-gd'
    - 'php5-json'
    - 'php5-mcrypt'
    - 'php5-memcache'
    - 'php5-mysqlnd'
    - 'php5-xdebug'
    - 'php5-xhprof'

php_disabled_modules:
  - apcu
  - blackfire
  - redis
  - xdebug
  - xhprof

php_enabled_modules:
  - mcrypt