---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart apache
  service: name=apache2 state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ntp
  service: name=ntp state=restarted
