---

- name: Add OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [ php-apcu, php-opcache, php-xdebug, php-blackfire ]

- name: Install Some PPAs - software-properties-common
  apt: name=software-properties-common state=present

- name: Add package repositories
  apt_repository: repo={{ item }}
  with_items:
    - "ppa:ondrej/{{ php_common_ppa }}"

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_common_packages

- name: Customize PHP fpm configuration file
  ini_file: dest={{ php_fpm_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini
  notify:
   - restart php-fpm

- name: Customize PHP cli configuration file
  ini_file: dest={{ php_cli_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini

- include: apcu.yml
  tags: php-apcu

- include: blackfire.yml
  tags: php-blackfire

- include: opcache.yml
  tags: php-opcache

- include: xdebug.yml
  tags: php-xdebug

- name: Enable php modules
  command: php5enmod {{ item }}
  with_items: php_enabled_modules
  notify:
    - restart php-fpm

- name: Disable php modules
  command: php5dismod {{ item }}
  with_items: php_disabled_modules
  notify:
    - restart php-fpm
